// module.exports = {
    
//     category:{
//         small_square: 's',
//         large_square: 'q'
//     },

//     product:{
//           POST_ADD_PRODUCT_REQUEST : 'POST_ADD_PRODUCT_REQUEST',
//           GET_ADD_PRODUCT_SUCCESS  : 'GET_ADD_PRODUCT_SUCCESS',
//           GET_ADD_PRODUCT_FAILURE  : 'GET_ADD_LOGIN_FAILURE',
//           POST_PRODUCTS_REQUEST    : 'POST_PRODUCTS_REQUEST',
//           GET_PRODUCTS_SUCCESS     : 'GET_PRODUCTS_SUCCESS',
//           GET_PRODUCTS_FAILURE     : 'GET_PRODUCTS_FAILURE'
//     }

// }

export const POST_ADD_PRODUCT_REQUEST   = 'POST_ADD_PRODUCT_REQUEST';
export const GET_ADD_PRODUCT_SUCCESS    = 'GET_ADD_PRODUCT_SUCCESS';
export const GET_ADD_PRODUCT_FAILURE    = 'GET_ADD_PRODUCT_FAILURE';

export const POST_PRODUCTS_REQUEST   = 'POST_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS    = 'GET_ADD_PRODUCT_SUCCESS';
export const GET_PRODUCTS_FAILURE    = 'GET_PRODUCTS_FAILURE';

export const POST_DELETE_PRODUCT_REQUEST   = 'POST_DELETE_PRODUCT_REQUEST';
export const GET_DELETE_PRODUCT_SUCCESS    = 'GET_DELETE_PRODUCT_SUCCESS';
export const GET_DELETE_PRODUCT_FAILURE    = 'GET_DELETE_PRODUCT_FAILURE';

export const POST_STATUS_PRODUCT_REQUEST   = 'POST_STATUS_PRODUCT_REQUEST';
export const GET_STATUS_PRODUCT_SUCCESS    = 'GET_STATUS_PRODUCT_SUCCESS';
export const GET_STATUS_PRODUCT_FAILURE    = 'GET_STATUS_PRODUCT_FAILURE';

export const POST_CREATE_PRODUCT_REQUEST   = 'POST_CREATE_PRODUCT_REQUEST';
export const GET_CREATE_PRODUCT_SUCCESS    = 'GET_CREATE_PRODUCT_SUCCESS';
export const GET_CREATE_PRODUCT_FAILURE    = 'GET_CREATE_PRODUCT_FAILURE';



